package:
  name: {{ environ.get('SINGA_NAME', 'singa') }}
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/apache/incubator-singa.git


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CONDA_BLD_PATH
    - SINGA_INCLUDE_PATH
    - SINGA_LIBRARY_PATH

requirements:
  build:
    - swig 3.0.2
    - openblas 0.2.19
    - protobuf 3.2.0
    - glog 0.3.4
    - libgfortran 3.0.0 # [osx]
    - gcc 4.8.5 # [linux]
    - python 2.7*
    - numpy 1.12.0

  run:
    - openblas 0.2.19
    - protobuf 3.2.0
    - glog 0.3.4
    - libgfortran 3.0.0 # [osx]
    - libgcc 4.8.5 # [linux]
    - python 2.7*
    - numpy >=1.12.0
    - flask >=0.10.1
    - flask-cors >=3.0.2
    - pillow >=2.3.0

about:
  home: http://singa.apache.org/
  license: Apache V2
  license_file: LICENSE
  summary: SINGA is an Apache Incubating project for providing distributed deep learning. Apache disclaimers http://singa.apache.org/en/index.html#disclaimers
