package:
  name: singa-gpu
  version: 1.1.1

requirements:
  run:
    - singa 1.1.1 py36_cuda9.0_cudnn7.1.2

about:
  home: http://singa.apache.org/
  license: Apache V2
  summary: SINGA is an Apache Incubating project for providing distributed deep learning. Apache disclaimers http://singa.apache.org/en/index.html#disclaimers
